title: Jordan Rice # your name (or website title) here
logo: "IMG_4740.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data analyst proficient in SQL and Tableau, adept at uncovering insights and driving informed decision-making through data-driven strategies. Skilled in querying databases, transforming complex data into actionable visualizations, and communicating findings effectively. Passionate about leveraging analytics to solve business challenges and optimize processes.
  <br><br>
  --------------------------------------------------
  <br><br>
  Prior experience in strategy consulting, business development, and project management. 
  <br><br>
  <a href="https://www.linkedin.com/in/jordan-rice-12b641124/">My LinkedIn</a> 
  <a href="https://github.com/jordanrrice">My Github</a> 



  
  
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
google_analytics: G-BSVYPQTYS2 # your Google Analytics tracking ID here
